name: testnew
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  # GetX state management
  get: ^4.3.8
  # local storage
  get_storage: ^2.0.3
  # rest api
  dio: ^4.0.0
  dio_retry_plus: ^0.0.2
  # image svg widget
  flutter_svg: ^0.22.0
  #image cache widget
  cached_network_image: ^3.1.0
  #google translation
  translator: ^0.1.7
  #money formatter
  money_formatter: ^0.0.3
  #keyboard dismisser
  keyboard_dismisser: ^2.0.0
  #sms auto fill
  sms_autofill: ^2.1.2
  #swipe to bottom refresh widget
  liquid_pull_to_refresh: ^3.0.0
  #cupertino effect
  bouncing_widget: ^2.0.0

  chuck_interceptor: ^0.0.8
  #database
  floor: ^1.2.0
  # search bar widget
  flutter_staggered_grid_view: ^0.4.0
  # internet connect
  connectivity: ^3.0.6

  full_screen_image_null_safe: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  floor_generator: any
  build_runner: ^2.1.4

flutter:

  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
    - assets/
